<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="IL-1270" name="com.deere.testCases.GSCTestCases" tests="1" failures="0" timestamp="16 Jul 2018 10:33:16 GMT" time="137.100" errors="1">
  <testcase name="test_TC6543_GSCCaseCoding" time="137.100" classname="com.deere.testCases.GSCTestCases">
    <error type="java.lang.AssertionError" message="Denied Assistance is not displayed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Denied Assistance is not displayed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.deere.global.CommonFunctions.assertTrue(CommonFunctions.java:1090)
	at com.deere.testCases.GSCTestCases.test_TC6543_GSCCaseCoding(GSCTestCases.java:2155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- test_TC6543_GSCCaseCoding -->
</testsuite> <!-- com.deere.testCases.GSCTestCases -->
